services:
  frontend:
    image: node:latest
    command: ["sh", "run_server.sh"]
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend/my-project:/app

  backend_app:
    image: python:3.12
    command: ["sh", "run_server.sh"]
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./backend/app:/app

  backend_model:
    image: pytorch/torchserve:latest
    command: ["sh", "run_server.sh"]
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 7070:7070
      - 7071:7071
    working_dir: /home/model-server
    volumes:
      - ./backend/model/model-store:/home/model-server/model-store
      - ./backend/model/script/run_server.sh:/home/model-server/run_server.sh
